@startuml

hide empty methods
hide empty fields
abstract class Student
{
    + name : string
    - age : int
    ~ sex : bool
    # exp : int
    
    Do() : void
}

House o-- Rooms
Car *-- Wheels

Teacher - Student : "1" insegna > "*"



@enduml
